-- Migration 0006: Add magicLoginToken column for guest checkout auto-login
-- This short-lived JWT is generated by the Stripe webhook after a guest purchase
-- and consumed by GET /api/auth/magic?token=... to set the session cookie.
ALTER TABLE `users` ADD `magicLoginToken` varchar(512);
